# Generated by Django 3.1 on 2021-08-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dish',
        ),
    ]
